--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="~/Pictures/Wallpapers/wallpaper.jpg"

-- Special
background="#0d0505"
foreground="#c2c0c0"
cursor="#c2c0c0"

-- Colors
color0="#0d0505"
color1="#A35A6C"
color2="#C16A7F"
color3="#AD887C"
color4="#BC7B81"
color5="#D0758A"
color6="#E27C95"
color7="#c2c0c0"
color8="#675555"
color9="#A35A6C"
color10="#C16A7F"
color11="#AD887C"
color12="#BC7B81"
color13="#D0758A"
color14="#E27C95"
color15="#c2c0c0"
