foreground         #c2c0c0
background         #0d0505
background_opacity 1.0
cursor             #c2c0c0

active_tab_foreground     #0d0505
active_tab_background     #c2c0c0
inactive_tab_foreground   #c2c0c0
inactive_tab_background   #0d0505

active_border_color   #c2c0c0
inactive_border_color #0d0505
bell_border_color     #A35A6C

color0       #0d0505
color8       #675555
color1       #A35A6C
color9       #A35A6C
color2       #C16A7F
color10      #C16A7F
color3       #AD887C
color11      #AD887C
color4       #BC7B81
color12      #BC7B81
color5       #D0758A
color13      #D0758A
color6       #E27C95
color14      #E27C95
color7       #c2c0c0
color15      #c2c0c0
