# Shell variables
# Generated by 'wal'
wallpaper="~/Pictures/Wallpapers/wallpaper.jpg"

# Special
background='#0d0505'
foreground='#c2c0c0'
cursor='#c2c0c0'

# Colors
color0='#0d0505'
color1='#A35A6C'
color2='#C16A7F'
color3='#AD887C'
color4='#BC7B81'
color5='#D0758A'
color6='#E27C95'
color7='#c2c0c0'
color8='#675555'
color9='#A35A6C'
color10='#C16A7F'
color11='#AD887C'
color12='#BC7B81'
color13='#D0758A'
color14='#E27C95'
color15='#c2c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
