[colors]
background = '#0d05058e'
black = '#0d0505'
blue = '#A35A6C'
cursor = '#c2c0c0'
cyan = '#C16A7F'
foreground = '#c2c0c0'
green = '#AD887C'
magenta = '#BC7B81'
red = '#D0758A'
tabs = '#c2c0c0'
tabs-active = '#E27C95'
white = '#c2c0c0'
yellow = '#c2c0c0'
dim-black = '#0d05058e'
dim-blue = '#A35A6C8e'
dim-cyan = '#C16A7F8e'
dim-foreground = '#c2c0c08e'
dim-green = '#AD887C8e'
dim-magenta = '#BC7B818e'
dim-red = '#D0758A8e'
dim-white = '#E27C958e'
dim-yellow = '#c2c0c08e'
light-black = '#A35A6C'
light-blue = '#C16A7F'
light-cyan = '#AD887C'
light-foreground = '#BC7B81'
light-green = '#D0758A'
light-magenta = '#E27C95'
light-red = '#c2c0c0'
light-white = '#A35A6C'
light-yellow = '#C16A7F'
