# pywal theme for ghostty

background = 0d0505
foreground = c2c0c0
cursor-color = c2c0c0
selection-background = c2c0c0
selection-foreground = 0d0505

palette = 0=#0d0505
palette = 1=#A35A6C
palette = 2=#C16A7F
palette = 3=#AD887C
palette = 4=#BC7B81
palette = 5=#D0758A
palette = 6=#E27C95
palette = 7=#c2c0c0
palette = 8=#675555
palette = 9=#A35A6C
palette = 10=#C16A7F
palette = 11=#AD887C
palette = 12=#BC7B81
palette = 13=#D0758A
palette = 14=#E27C95
palette = 15=#c2c0c0
